### ISSUE TITLE
How to run this application in production mode

### ISSUE THREAD

**Issue by jsandeepm** [zombiQWERTY/angular-webpack-babel-postcss-jade-livereload-workflow#1]
Hi,

If I run 

npm start : it will run web-dev-server in development mode

npm build : it will prepare bundle.

But how to run in production mode?

So that 

var isProd = ENV === 'build';

should return "isProd = true."

**Comment by zombiQWERTY** [comment]
Hello.
Sorry for long answering delay.
Look on `process.env.npm_lifecycle_event`
