### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [zombiQWERTY/angular-webpack-babel-postcss-jade-livereload-workflow#2]
when i hit localhost:8080 after npm start. it shows the following attached error.
![error](https://user-images.githubusercontent.com/19573094/27514127-b426987e-599e-11e7-89b8-ce0afc4bb0c9.png)

**Comment by zombiQWERTY** [comment]
Use Vue or React instead of Angular (especially 1.xx), bro
